fileVersion: 1
id: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
name: V_TICKET_FIELD_HISTORY_FILL_VALUES
operation:
  config:
    OverrideSQLCreate: false
    groupByAll: false
    insertStrategy: UNION
    secureoption: false
    selectDistinct: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dd42f3a4-ed8d-4880-bca0-b632e4ce9c94
          stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
        config: {}
        dataType: DATE
        description: ""
        name: DATE_KEY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 474ac3a7-2f85-423f-a18a-b3f63fcc14ca
                stepCounter: 44467244-350f-4483-8937-af6878cba280
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 204e23cb-7554-4afa-8197-48bd2c4e2e93
          stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
        config: {}
        dataType: NUMBER(38,0)
        description: ""
        name: TICKET_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b65d9400-4f01-4873-8e35-a1cbb988a303
                stepCounter: 44467244-350f-4483-8937-af6878cba280
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 33f4ebdb-cc0c-4994-ba09-b8ccb698485d
          stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
        config: {}
        dataType: ""
        description: ""
        name: STATUS
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 386e4342-b6fd-4a2a-8b1e-d0b8803bfdb1
                stepCounter: 44467244-350f-4483-8937-af6878cba280
            transform: |-
              first_value( status ) over (
                          partition by ticket_id, status_field_partition 
                          order by date_KEY asc rows between unbounded preceding and current row) 
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5d65b67a-f539-4f2b-abdb-01508a863263
          stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
        config: {}
        dataType: ""
        description: ""
        name: ASSIGNEE_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 11cb8803-f9d3-45e8-afce-f81c0b64c48a
                stepCounter: 44467244-350f-4483-8937-af6878cba280
            transform: |-
              first_value( assignee_id ) over (
                          partition by ticket_id, assignee_id_field_partition 
                          order by date_KEY asc rows between unbounded preceding and current row)
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 141e0d4d-490f-4314-b3a0-cb34a9c0712e
          stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
        config: {}
        dataType: ""
        description: ""
        name: PRIORITY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: abf27897-c625-4f4c-966f-c2497235f441
                stepCounter: 44467244-350f-4483-8937-af6878cba280
            transform: |-
              first_value( priority ) over (
                          partition by ticket_id, priority_field_partition 
                          order by date_KEY asc rows between unbounded preceding and current row)
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: V_TICKET_FIELD_HISTORY_SET_VALUES
        join:
          joinCondition: FROM {{ ref('TARGET', 'V_TICKET_FIELD_HISTORY_SET_VALUES') }} "V_TICKET_FIELD_HISTORY_SET_VALUES"
        name: V_TICKET_FIELD_HISTORY_FILL_VALUES
        noLinkRefs: []
  name: V_TICKET_FIELD_HISTORY_FILL_VALUES
  overrideSQL: false
  schema: ""
  sqlType: Base:::188
  type: sql
  version: 1
type: Node
