fileVersion: 1
id: b77d9e8d-d483-4658-aff9-6b191a24366c
name: V_SET_VALUES
operation:
  config:
    OverrideSQLCreate: false
    groupByAll: false
    insertStrategy: UNION
    secureoption: false
    selectDistinct: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: be9e5424-3c39-4844-a044-23712763069a
          stepCounter: b77d9e8d-d483-4658-aff9-6b191a24366c
        config: {}
        dataType: ""
        description: ""
        name: VALID_FROM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fbc8b059-2bfb-4f66-a122-6af90234f63c
                stepCounter: 3b80ea28-5325-4788-bd50-cb810561ffbd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ee239817-8464-49e9-ac3a-57a6c6a01f24
          stepCounter: b77d9e8d-d483-4658-aff9-6b191a24366c
        config: {}
        dataType: NUMBER(38,0)
        description: ""
        name: TICKET_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c9160a9c-6472-45b7-940c-d5dfba47941c
                stepCounter: 3b80ea28-5325-4788-bd50-cb810561ffbd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3d9d0d5c-c598-48d7-9b6e-b8c00d36b021
          stepCounter: b77d9e8d-d483-4658-aff9-6b191a24366c
        config: {}
        dataType: ""
        description: ""
        name: TICKET_DAY_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ff464ab2-43eb-43cc-a4e7-cd32b0f26095
                stepCounter: 3b80ea28-5325-4788-bd50-cb810561ffbd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 917436a7-9659-4898-b7e3-a87e70d7e355
          stepCounter: b77d9e8d-d483-4658-aff9-6b191a24366c
        config: {}
        dataType: ""
        description: ""
        name: STATUS
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e227b872-4424-43a2-9420-704129252b59
                stepCounter: 3b80ea28-5325-4788-bd50-cb810561ffbd
            transform: ""
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 61d052db-9197-4501-ad53-ca3837dbe65f
          stepCounter: b77d9e8d-d483-4658-aff9-6b191a24366c
        config: {}
        dataType: ""
        defaultValue: ""
        description: ""
        name: STATUS_FIELD_PARTITION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: |-
              sum(case when status is null 
                              then 0 
                              else 1 
                                  end) over (order by ticket_id, date_day rows unbounded preceding)
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 27e2df76-6ade-4ba9-bd3a-a75ce0841619
          stepCounter: b77d9e8d-d483-4658-aff9-6b191a24366c
        config: {}
        dataType: ""
        description: ""
        name: ASSIGNEE_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0ef3342f-51e6-4e17-b64d-84de72501879
                stepCounter: 3b80ea28-5325-4788-bd50-cb810561ffbd
            transform: ""
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 9ace2fd3-da95-477f-ac27-85d50d4ee6f8
          stepCounter: b77d9e8d-d483-4658-aff9-6b191a24366c
        config: {}
        dataType: ""
        defaultValue: ""
        description: ""
        name: ASSIGNEE_ID_FIELD_PARTITION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: |-
              Sum(case when assignee_id is null 
                              then 0 
                              else 1 
                                  end) over (order by ticket_id, date_day rows unbounded preceding) 
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 98cf47a1-8f1c-43b8-836e-ef3f7552e1e4
          stepCounter: b77d9e8d-d483-4658-aff9-6b191a24366c
        config: {}
        dataType: ""
        description: ""
        name: PRIORITY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2d07c465-8dad-40d2-996b-ad6ac0e3c8e5
                stepCounter: 3b80ea28-5325-4788-bd50-cb810561ffbd
            transform: ""
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b8f3ffa9-1640-499c-8d30-ddc8830fdb4f
          stepCounter: b77d9e8d-d483-4658-aff9-6b191a24366c
        config: {}
        dataType: ""
        defaultValue: ""
        description: ""
        name: PRIORITY_FIELD_PARTITION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: |-
              sum(case when priority is null 
                              then 0 
                              else 1 
                                  end) over (order by ticket_id, date_day rows unbounded preceding)
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: V_INT_FIELD_HISTORY_PIVOT
        join:
          joinCondition: FROM {{ ref('TARGET', 'V_INT_FIELD_HISTORY_PIVOT') }} "V_INT_FIELD_HISTORY_PIVOT"
        name: V_SET_VALUES
        noLinkRefs: []
  name: V_SET_VALUES
  overrideSQL: false
  schema: ""
  sqlType: Base:::188
  type: sql
  version: 1
type: Node
