fileVersion: 1
id: 307a796f-dd51-42cb-9063-12b41ea639bf
name: V_TICKET_FIELD_HISTORY_FIX_NULL_VALUES
operation:
  config:
    OverrideSQLCreate: false
    groupByAll: false
    insertStrategy: UNION
    secureoption: false
    selectDistinct: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6fb4004b-a063-46d0-88bc-57323f5cd06a
          stepCounter: 307a796f-dd51-42cb-9063-12b41ea639bf
        config: {}
        dataType: DATE
        description: ""
        name: DATE_KEY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: dd42f3a4-ed8d-4880-bca0-b632e4ce9c94
                stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b465719e-b54e-4615-8f47-166c0a682c3f
          stepCounter: 307a796f-dd51-42cb-9063-12b41ea639bf
        config: {}
        dataType: NUMBER(38,0)
        description: ""
        name: TICKET_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 204e23cb-7554-4afa-8197-48bd2c4e2e93
                stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7d1cad76-c09f-490f-8db2-197680c9f911
          stepCounter: 307a796f-dd51-42cb-9063-12b41ea639bf
        config: {}
        dataType: ""
        description: ""
        name: STATUS
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 33f4ebdb-cc0c-4994-ba09-b8ccb698485d
                stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
            transform: case when  cast( status as TEXT ) = 'is_null' then null else status end
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 60ca6ed1-4b82-4308-9d2f-f61ed062e2a1
          stepCounter: 307a796f-dd51-42cb-9063-12b41ea639bf
        config: {}
        dataType: ""
        description: ""
        name: ASSIGNEE_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5d65b67a-f539-4f2b-abdb-01508a863263
                stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
            transform: case when  cast( assignee_id as TEXT ) = 'is_null' then null else assignee_id end
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1a54f0d6-f4a9-4dd3-b44b-462853693466
          stepCounter: 307a796f-dd51-42cb-9063-12b41ea639bf
        config: {}
        dataType: ""
        description: ""
        name: PRIORITY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 141e0d4d-490f-4314-b3a0-cb34a9c0712e
                stepCounter: 1dc87b2d-8f6f-4e1d-8854-af4e4437c4be
            transform: case when  cast( priority as TEXT ) = 'is_null' then null else priority end
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: V_TICKET_FIELD_HISTORY_FILL_VALUES
        join:
          joinCondition: FROM {{ ref('TARGET', 'V_TICKET_FIELD_HISTORY_FILL_VALUES') }} "V_TICKET_FIELD_HISTORY_FILL_VALUES"
        name: V_TICKET_FIELD_HISTORY_FIX_NULL_VALUES
        noLinkRefs: []
  name: V_TICKET_FIELD_HISTORY_FIX_NULL_VALUES
  overrideSQL: false
  schema: ""
  sqlType: Base:::188
  type: sql
  version: 1
type: Node
